name: dependency-graph

on:
  push:
    branches:
      - main

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - uses: coursier/cache-action@v6
    
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
    
      - uses: ckipp01/mill-dependency-submission@v1
